
package desktoptest;

import java.sql.*;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

public class Employes extends javax.swing.JFrame {

    /** Creates new form Employes */
    public Employes() {
        initComponents();
        Connection con;
        Functions action=new Functions();
        con=action.Connect_db();
        
       action.Affiche(con, table_employe);
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        psalaire = new javax.swing.JPanel();
        salaire = new javax.swing.JLabel();
        Empl = new javax.swing.JPanel();
        empl2 = new javax.swing.JLabel();
        Pointage = new javax.swing.JPanel();
        point2 = new javax.swing.JLabel();
        CONGE = new javax.swing.JPanel();
        Conge2 = new javax.swing.JLabel();
        ppdf = new javax.swing.JPanel();
        pdf = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        chnum1 = new javax.swing.JTextField();
        chnom1 = new javax.swing.JTextField();
        chprenom1 = new javax.swing.JTextField();
        chposte1 = new javax.swing.JTextField();
        chsalaire1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        pajouter = new javax.swing.JPanel();
        ajouter1 = new javax.swing.JLabel();
        supprimer = new javax.swing.JPanel();
        supprimer1 = new javax.swing.JLabel();
        pannuler = new javax.swing.JPanel();
        modifier1 = new javax.swing.JLabel();
        pmodifier = new javax.swing.JPanel();
        modifier3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_employe = new javax.swing.JTable();
        search_Nom = new javax.swing.JTextField();
        search = new javax.swing.JButton();

        popupMenu1.setLabel("lol");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1300, 700));
        jPanel1.setMinimumSize(new java.awt.Dimension(1300, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 700));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setMaximumSize(new java.awt.Dimension(254, 600));
        jPanel2.setMinimumSize(new java.awt.Dimension(254, 600));

        jLabel2.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Entreprise Art'Soa");

        psalaire.setBackground(new java.awt.Color(255, 255, 255));
        psalaire.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                psalaireMousePressed(evt);
            }
        });

        salaire.setBackground(new java.awt.Color(255, 255, 255));
        salaire.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        salaire.setForeground(new java.awt.Color(0, 102, 102));
        salaire.setText("SALAIRE");
        salaire.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                salaireMousePressed(evt);
            }
        });

        javax.swing.GroupLayout psalaireLayout = new javax.swing.GroupLayout(psalaire);
        psalaire.setLayout(psalaireLayout);
        psalaireLayout.setHorizontalGroup(
            psalaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 202, Short.MAX_VALUE)
            .addGroup(psalaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(psalaireLayout.createSequentialGroup()
                    .addGap(0, 67, Short.MAX_VALUE)
                    .addComponent(salaire)
                    .addGap(0, 68, Short.MAX_VALUE)))
        );
        psalaireLayout.setVerticalGroup(
            psalaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
            .addGroup(psalaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(psalaireLayout.createSequentialGroup()
                    .addGap(0, 8, Short.MAX_VALUE)
                    .addComponent(salaire)
                    .addGap(0, 9, Short.MAX_VALUE)))
        );

        Empl.setBackground(new java.awt.Color(255, 255, 255));
        Empl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EmplMousePressed(evt);
            }
        });
        Empl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EmplKeyReleased(evt);
            }
        });

        empl2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        empl2.setForeground(new java.awt.Color(0, 102, 102));
        empl2.setText("EMPLOYE");
        empl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                empl2MousePressed(evt);
            }
        });
        empl2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                empl2KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout EmplLayout = new javax.swing.GroupLayout(Empl);
        Empl.setLayout(EmplLayout);
        EmplLayout.setHorizontalGroup(
            EmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(EmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(EmplLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(empl2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        EmplLayout.setVerticalGroup(
            EmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
            .addGroup(EmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(EmplLayout.createSequentialGroup()
                    .addGap(0, 9, Short.MAX_VALUE)
                    .addComponent(empl2)
                    .addGap(0, 8, Short.MAX_VALUE)))
        );

        Pointage.setBackground(new java.awt.Color(255, 255, 255));
        Pointage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PointageMousePressed(evt);
            }
        });
        Pointage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PointageKeyReleased(evt);
            }
        });

        point2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        point2.setForeground(new java.awt.Color(0, 102, 102));
        point2.setText("POINTAGE");
        point2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                point2MousePressed(evt);
            }
        });
        point2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                point2KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout PointageLayout = new javax.swing.GroupLayout(Pointage);
        Pointage.setLayout(PointageLayout);
        PointageLayout.setHorizontalGroup(
            PointageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(PointageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PointageLayout.createSequentialGroup()
                    .addGap(0, 59, Short.MAX_VALUE)
                    .addComponent(point2)
                    .addGap(0, 59, Short.MAX_VALUE)))
        );
        PointageLayout.setVerticalGroup(
            PointageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
            .addGroup(PointageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PointageLayout.createSequentialGroup()
                    .addGap(0, 8, Short.MAX_VALUE)
                    .addComponent(point2)
                    .addGap(0, 9, Short.MAX_VALUE)))
        );

        CONGE.setBackground(new java.awt.Color(255, 255, 255));
        CONGE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CONGEMousePressed(evt);
            }
        });

        Conge2.setBackground(new java.awt.Color(255, 255, 255));
        Conge2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Conge2.setForeground(new java.awt.Color(0, 102, 102));
        Conge2.setText("CONGE");
        Conge2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Conge2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout CONGELayout = new javax.swing.GroupLayout(CONGE);
        CONGE.setLayout(CONGELayout);
        CONGELayout.setHorizontalGroup(
            CONGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(CONGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CONGELayout.createSequentialGroup()
                    .addGap(0, 71, Short.MAX_VALUE)
                    .addComponent(Conge2)
                    .addGap(0, 72, Short.MAX_VALUE)))
        );
        CONGELayout.setVerticalGroup(
            CONGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
            .addGroup(CONGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CONGELayout.createSequentialGroup()
                    .addGap(0, 8, Short.MAX_VALUE)
                    .addComponent(Conge2)
                    .addGap(0, 9, Short.MAX_VALUE)))
        );

        ppdf.setBackground(new java.awt.Color(255, 255, 255));
        ppdf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ppdfMousePressed(evt);
            }
        });

        pdf.setBackground(new java.awt.Color(255, 255, 255));
        pdf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pdf.setForeground(new java.awt.Color(0, 102, 102));
        pdf.setText("PDF");
        pdf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pdfMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ppdfLayout = new javax.swing.GroupLayout(ppdf);
        ppdf.setLayout(ppdfLayout);
        ppdfLayout.setHorizontalGroup(
            ppdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 202, Short.MAX_VALUE)
            .addGroup(ppdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ppdfLayout.createSequentialGroup()
                    .addContainerGap(85, Short.MAX_VALUE)
                    .addComponent(pdf, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(70, Short.MAX_VALUE)))
        );
        ppdfLayout.setVerticalGroup(
            ppdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
            .addGroup(ppdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ppdfLayout.createSequentialGroup()
                    .addContainerGap(8, Short.MAX_VALUE)
                    .addComponent(pdf)
                    .addContainerGap(9, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ppdf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Pointage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Empl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CONGE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(psalaire, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(Empl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(Pointage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(CONGE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(psalaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(ppdf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestion des employés");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        chnum1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        chnum1.setMaximumSize(new java.awt.Dimension(50, 18));
        chnum1.setMinimumSize(new java.awt.Dimension(50, 18));
        chnum1.setPreferredSize(new java.awt.Dimension(50, 18));
        chnum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chnum1ActionPerformed(evt);
            }
        });

        chnom1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        chnom1.setMaximumSize(new java.awt.Dimension(50, 18));
        chnom1.setMinimumSize(new java.awt.Dimension(50, 18));
        chnom1.setPreferredSize(new java.awt.Dimension(50, 18));
        chnom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chnom1ActionPerformed(evt);
            }
        });

        chprenom1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        chprenom1.setMaximumSize(new java.awt.Dimension(50, 18));
        chprenom1.setMinimumSize(new java.awt.Dimension(50, 18));
        chprenom1.setPreferredSize(new java.awt.Dimension(50, 18));
        chprenom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chprenom1ActionPerformed(evt);
            }
        });

        chposte1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        chposte1.setMaximumSize(new java.awt.Dimension(50, 18));
        chposte1.setMinimumSize(new java.awt.Dimension(50, 18));
        chposte1.setPreferredSize(new java.awt.Dimension(50, 18));
        chposte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chposte1ActionPerformed(evt);
            }
        });

        chsalaire1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        chsalaire1.setMaximumSize(new java.awt.Dimension(50, 18));
        chsalaire1.setMinimumSize(new java.awt.Dimension(50, 18));
        chsalaire1.setPreferredSize(new java.awt.Dimension(50, 18));
        chsalaire1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chsalaire1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Id");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Nom");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Prenom");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Poste");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Salaire");

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        pajouter.setBackground(new java.awt.Color(0, 102, 102));
        pajouter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pajouter.setForeground(new java.awt.Color(255, 255, 255));
        pajouter.setMaximumSize(new java.awt.Dimension(250, 40));
        pajouter.setMinimumSize(new java.awt.Dimension(250, 40));
        pajouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pajouterMousePressed(evt);
            }
        });

        ajouter1.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        ajouter1.setForeground(new java.awt.Color(255, 255, 255));
        ajouter1.setText("AJOUTER");
        ajouter1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ajouter1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout pajouterLayout = new javax.swing.GroupLayout(pajouter);
        pajouter.setLayout(pajouterLayout);
        pajouterLayout.setHorizontalGroup(
            pajouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pajouterLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(ajouter1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pajouterLayout.setVerticalGroup(
            pajouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pajouterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ajouter1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        supprimer.setBackground(new java.awt.Color(0, 102, 102));
        supprimer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        supprimer.setForeground(new java.awt.Color(255, 255, 255));
        supprimer.setMaximumSize(new java.awt.Dimension(250, 40));
        supprimer.setMinimumSize(new java.awt.Dimension(250, 40));
        supprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                supprimerMousePressed(evt);
            }
        });

        supprimer1.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        supprimer1.setForeground(new java.awt.Color(255, 255, 255));
        supprimer1.setText("SUPPRIMER");
        supprimer1.setMaximumSize(new java.awt.Dimension(250, 40));
        supprimer1.setMinimumSize(new java.awt.Dimension(250, 40));
        supprimer1.setPreferredSize(new java.awt.Dimension(250, 40));
        supprimer1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                supprimer1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout supprimerLayout = new javax.swing.GroupLayout(supprimer);
        supprimer.setLayout(supprimerLayout);
        supprimerLayout.setHorizontalGroup(
            supprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supprimerLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(supprimer1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        supprimerLayout.setVerticalGroup(
            supprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supprimerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(supprimer1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pannuler.setBackground(new java.awt.Color(0, 102, 102));
        pannuler.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pannuler.setForeground(new java.awt.Color(255, 255, 255));
        pannuler.setMaximumSize(new java.awt.Dimension(250, 40));
        pannuler.setMinimumSize(new java.awt.Dimension(250, 40));
        pannuler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pannulerMousePressed(evt);
            }
        });

        modifier1.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        modifier1.setForeground(new java.awt.Color(255, 255, 255));
        modifier1.setText("ANNULER");
        modifier1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                modifier1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout pannulerLayout = new javax.swing.GroupLayout(pannuler);
        pannuler.setLayout(pannulerLayout);
        pannulerLayout.setHorizontalGroup(
            pannulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannulerLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(modifier1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pannulerLayout.setVerticalGroup(
            pannulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannulerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(modifier1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pmodifier.setBackground(new java.awt.Color(0, 102, 102));
        pmodifier.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pmodifier.setForeground(new java.awt.Color(255, 255, 255));
        pmodifier.setMaximumSize(new java.awt.Dimension(250, 40));
        pmodifier.setMinimumSize(new java.awt.Dimension(250, 40));
        pmodifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pmodifierMousePressed(evt);
            }
        });

        modifier3.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        modifier3.setForeground(new java.awt.Color(255, 255, 255));
        modifier3.setText("MODIFIER");
        modifier3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                modifier3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout pmodifierLayout = new javax.swing.GroupLayout(pmodifier);
        pmodifier.setLayout(pmodifierLayout);
        pmodifierLayout.setHorizontalGroup(
            pmodifierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pmodifierLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(modifier3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pmodifierLayout.setVerticalGroup(
            pmodifierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pmodifierLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(modifier3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pmodifier, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pannuler, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(pajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pmodifier, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pannuler, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        table_employe.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        table_employe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numéro empoyé", "Nom", "Prenom", "Poste", "Salaire"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_employe.setGridColor(new java.awt.Color(0, 102, 102));
        table_employe.setSelectionBackground(new java.awt.Color(0, 102, 102));
        table_employe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_employeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table_employeMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(table_employe);

        search_Nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_NomActionPerformed(evt);
            }
        });

        search.setBackground(new java.awt.Color(0, 102, 102));
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("Search");
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                searchMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5))
                                    .addGap(23, 23, 23))
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chsalaire1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chposte1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chprenom1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chnom1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chnum1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(113, 113, 113)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(search_Nom, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 95, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chnum1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chnom1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chprenom1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chposte1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chsalaire1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search)
                    .addComponent(search_Nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 660));

        setSize(new java.awt.Dimension(1244, 672));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chnum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chnum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chnum1ActionPerformed

    private void chnom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chnom1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chnom1ActionPerformed

    private void chprenom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chprenom1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chprenom1ActionPerformed

    private void chposte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chposte1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chposte1ActionPerformed

    private void chsalaire1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chsalaire1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chsalaire1ActionPerformed

    private void ajouter1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajouter1MousePressed
        Connection con;
        Functions action=new Functions();
        con=action.Connect_db();

        action.Affiche(con, table_employe);
        action.InsertTable(con, chnum1, chnom1, chprenom1, chposte1, chsalaire1);
        action.Affiche(con, table_employe);
    }//GEN-LAST:event_ajouter1MousePressed

    private void pajouterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pajouterMousePressed
        Connection con;
        Functions action=new Functions();
        con=action.Connect_db();

        action.Affiche(con, table_employe);
        action.InsertTable(con, chnum1, chnom1, chprenom1, chposte1, chsalaire1);
        action.Affiche(con, table_employe);
    }//GEN-LAST:event_pajouterMousePressed

    private void supprimer1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supprimer1MousePressed
        Connection con;
        Functions action=new Functions();
        con=action.Connect_db();

        action.Delete(con, table_employe, chnum1);
        action.Affiche(con, table_employe);
    }//GEN-LAST:event_supprimer1MousePressed

    private void supprimerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supprimerMousePressed
        Connection con;
        Functions action=new Functions();
        con=action.Connect_db();
        action.Delete(con, table_employe, chnum1);
        action.Affiche(con, table_employe);
    }//GEN-LAST:event_supprimerMousePressed

    private void modifier1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifier1MousePressed
        Connection con;
        Functions action=new Functions();
        con=action.Connect_db();

       action.Annuler(chnum1, chnom1, chprenom1, chposte1, chsalaire1);
    }//GEN-LAST:event_modifier1MousePressed

    private void pannulerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pannulerMousePressed
        Connection con;
        Functions action=new Functions();
        con=action.Connect_db();

        action.Annuler(chnum1, chnom1, chprenom1, chposte1, chsalaire1);
    }//GEN-LAST:event_pannulerMousePressed

    private void table_employeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_employeMouseClicked

    }//GEN-LAST:event_table_employeMouseClicked

    private void table_employeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_employeMousePressed
        try {
            Connection con;
            Functions action=new Functions();
            con=action.Connect_db();
            String id=action.getId(con, table_employe);

            action.Affiche(con, table_employe);
            action.Update_1(con, id, table_employe, chnum1, chnom1, chprenom1, chposte1, chsalaire1);
           action.Affiche(con, table_employe);
        } catch (SQLException ex) {
            Logger.getLogger(Employes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_table_employeMousePressed

    private void modifier3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifier3MousePressed
       Connection con;
        Functions action=new Functions();
        con=action.Connect_db();
     
        action.Affiche(con, table_employe);
        action.Update_2(con, chnum1, chnom1, chprenom1, chposte1, chsalaire1);
        action.Affiche(con, table_employe);
    }//GEN-LAST:event_modifier3MousePressed

    private void pmodifierMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pmodifierMousePressed
        Connection con;
        Functions action=new Functions();
        con=action.Connect_db();

        action.Affiche(con, table_employe);
        action.Update_2(con, chnum1, chnom1, chprenom1, chposte1, chsalaire1);
        action.Affiche(con, table_employe);
    }//GEN-LAST:event_pmodifierMousePressed

    private void salaireMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salaireMousePressed
        Salaire_actu salaire= new Salaire_actu();
        salaire.setVisible(true);
    }//GEN-LAST:event_salaireMousePressed

    private void psalaireMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psalaireMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_psalaireMousePressed

    private void empl2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empl2MousePressed
        Employes au=new Employes();
        au.setVisible(true);
    }//GEN-LAST:event_empl2MousePressed

    private void empl2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_empl2KeyReleased

    }//GEN-LAST:event_empl2KeyReleased

    private void EmplMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmplMousePressed
        Employes au=new Employes();
        au.setVisible(true);
    }//GEN-LAST:event_EmplMousePressed

    private void EmplKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmplKeyReleased

    }//GEN-LAST:event_EmplKeyReleased

    private void point2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_point2MousePressed
        Pointage au=new Pointage();
        au.setVisible(true);
    }//GEN-LAST:event_point2MousePressed

    private void point2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_point2KeyReleased

    }//GEN-LAST:event_point2KeyReleased

    private void PointageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PointageMousePressed
        Pointage au=new Pointage();
        au.setVisible(true);
    }//GEN-LAST:event_PointageMousePressed

    private void PointageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PointageKeyReleased

    }//GEN-LAST:event_PointageKeyReleased

    private void Conge2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Conge2MousePressed
        Conge au=new Conge();
        au.setVisible(true);
    }//GEN-LAST:event_Conge2MousePressed

    private void CONGEMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CONGEMousePressed
        Conge au=new Conge();
        au.setVisible(true);
    }//GEN-LAST:event_CONGEMousePressed

    private void search_NomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_NomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_NomActionPerformed

    private void pdfMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pdfMousePressed
     PdfqPayement pdf=new PdfqPayement();
     pdf.setVisible(true);
    }//GEN-LAST:event_pdfMousePressed

    private void ppdfMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ppdfMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ppdfMousePressed

    private void searchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMousePressed
        Connection con;
        Functions action=new Functions();
        Functions_2 action2=new Functions_2();
        con=action.Connect_db();
        
        table_employe.setVisible(false);
        action2.Recherche(con, table_employe, search_Nom);
        table_employe.setVisible(true);
        
    }//GEN-LAST:event_searchMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employes().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CONGE;
    private javax.swing.JLabel Conge2;
    private javax.swing.JPanel Empl;
    private javax.swing.JPanel Pointage;
    private javax.swing.JLabel ajouter1;
    private javax.swing.JTextField chnom1;
    private javax.swing.JTextField chnum1;
    private javax.swing.JTextField chposte1;
    private javax.swing.JTextField chprenom1;
    private javax.swing.JTextField chsalaire1;
    private javax.swing.JLabel empl2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel modifier1;
    private javax.swing.JLabel modifier3;
    private javax.swing.JPanel pajouter;
    private javax.swing.JPanel pannuler;
    private javax.swing.JLabel pdf;
    private javax.swing.JPanel pmodifier;
    private javax.swing.JLabel point2;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JPanel ppdf;
    private javax.swing.JPanel psalaire;
    private javax.swing.JLabel salaire;
    private javax.swing.JButton search;
    private javax.swing.JTextField search_Nom;
    private javax.swing.JPanel supprimer;
    private javax.swing.JLabel supprimer1;
    private javax.swing.JTable table_employe;
    // End of variables declaration//GEN-END:variables

}
