/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package desktoptest;
import java.sql.*;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
public class Pointage extends javax.swing.JFrame {

    /**
     * Creates new form Pointage
     */
    public Pointage() {
        initComponents();
        Connection con;
        Functions action=new Functions();
        con=action.Connect_db();
        
        action.Affiche2(con, table2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pabsence = new javax.swing.JPanel();
        absence = new javax.swing.JLabel();
        Empl = new javax.swing.JPanel();
        empl2 = new javax.swing.JLabel();
        Pointage = new javax.swing.JPanel();
        point2 = new javax.swing.JLabel();
        CONGE = new javax.swing.JPanel();
        Conge2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pointage_date = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pointage_empl = new javax.swing.JTextField();
        pointage_point = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        pajouter2 = new javax.swing.JPanel();
        ajouter2 = new javax.swing.JLabel();
        psupprimer2 = new javax.swing.JPanel();
        supprimer2 = new javax.swing.JLabel();
        pmodifier2 = new javax.swing.JPanel();
        modifier2 = new javax.swing.JLabel();
        pannuler2 = new javax.swing.JPanel();
        annuler2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1300, 700));
        jPanel1.setMinimumSize(new java.awt.Dimension(1300, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 700));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setMaximumSize(new java.awt.Dimension(254, 600));
        jPanel2.setMinimumSize(new java.awt.Dimension(254, 600));

        jLabel2.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Entreprise Art'Soa");

        pabsence.setBackground(new java.awt.Color(255, 255, 255));
        pabsence.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pabsenceMousePressed(evt);
            }
        });

        absence.setBackground(new java.awt.Color(255, 255, 255));
        absence.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        absence.setForeground(new java.awt.Color(0, 102, 102));
        absence.setText("ABSENCE");
        absence.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                absenceMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pabsenceLayout = new javax.swing.GroupLayout(pabsence);
        pabsence.setLayout(pabsenceLayout);
        pabsenceLayout.setHorizontalGroup(
            pabsenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 209, Short.MAX_VALUE)
            .addGroup(pabsenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pabsenceLayout.createSequentialGroup()
                    .addGap(0, 67, Short.MAX_VALUE)
                    .addComponent(absence)
                    .addGap(0, 68, Short.MAX_VALUE)))
        );
        pabsenceLayout.setVerticalGroup(
            pabsenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
            .addGroup(pabsenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pabsenceLayout.createSequentialGroup()
                    .addGap(0, 8, Short.MAX_VALUE)
                    .addComponent(absence)
                    .addGap(0, 9, Short.MAX_VALUE)))
        );

        Empl.setBackground(new java.awt.Color(255, 255, 255));
        Empl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EmplMousePressed(evt);
            }
        });
        Empl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EmplKeyReleased(evt);
            }
        });

        empl2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        empl2.setForeground(new java.awt.Color(0, 102, 102));
        empl2.setText("EMPLOYE");
        empl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                empl2MousePressed(evt);
            }
        });
        empl2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                empl2KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout EmplLayout = new javax.swing.GroupLayout(Empl);
        Empl.setLayout(EmplLayout);
        EmplLayout.setHorizontalGroup(
            EmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(EmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(EmplLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(empl2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        EmplLayout.setVerticalGroup(
            EmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
            .addGroup(EmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(EmplLayout.createSequentialGroup()
                    .addGap(0, 9, Short.MAX_VALUE)
                    .addComponent(empl2)
                    .addGap(0, 8, Short.MAX_VALUE)))
        );

        Pointage.setBackground(new java.awt.Color(255, 255, 255));
        Pointage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PointageMousePressed(evt);
            }
        });
        Pointage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PointageKeyReleased(evt);
            }
        });

        point2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        point2.setForeground(new java.awt.Color(0, 102, 102));
        point2.setText("POINTAGE");
        point2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                point2MousePressed(evt);
            }
        });
        point2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                point2KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout PointageLayout = new javax.swing.GroupLayout(Pointage);
        Pointage.setLayout(PointageLayout);
        PointageLayout.setHorizontalGroup(
            PointageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(PointageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PointageLayout.createSequentialGroup()
                    .addGap(0, 59, Short.MAX_VALUE)
                    .addComponent(point2)
                    .addGap(0, 59, Short.MAX_VALUE)))
        );
        PointageLayout.setVerticalGroup(
            PointageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
            .addGroup(PointageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PointageLayout.createSequentialGroup()
                    .addGap(0, 8, Short.MAX_VALUE)
                    .addComponent(point2)
                    .addGap(0, 9, Short.MAX_VALUE)))
        );

        CONGE.setBackground(new java.awt.Color(255, 255, 255));
        CONGE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CONGEMousePressed(evt);
            }
        });

        Conge2.setBackground(new java.awt.Color(255, 255, 255));
        Conge2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Conge2.setForeground(new java.awt.Color(0, 102, 102));
        Conge2.setText("CONGE");
        Conge2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Conge2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout CONGELayout = new javax.swing.GroupLayout(CONGE);
        CONGE.setLayout(CONGELayout);
        CONGELayout.setHorizontalGroup(
            CONGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(CONGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CONGELayout.createSequentialGroup()
                    .addGap(0, 71, Short.MAX_VALUE)
                    .addComponent(Conge2)
                    .addGap(0, 72, Short.MAX_VALUE)))
        );
        CONGELayout.setVerticalGroup(
            CONGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
            .addGroup(CONGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CONGELayout.createSequentialGroup()
                    .addGap(0, 8, Short.MAX_VALUE)
                    .addComponent(Conge2)
                    .addGap(0, 9, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Pointage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Empl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CONGE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pabsence, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(Empl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(Pointage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(CONGE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(pabsence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Gestion de pointage");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        pointage_date.setDateFormatString("yyyy-MM-dd");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Date de Pointage");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("N° Employé");

        pointage_empl.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        pointage_empl.setMaximumSize(new java.awt.Dimension(50, 18));
        pointage_empl.setMinimumSize(new java.awt.Dimension(50, 18));
        pointage_empl.setPreferredSize(new java.awt.Dimension(50, 18));
        pointage_empl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointage_emplActionPerformed(evt);
            }
        });

        pointage_point.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        pointage_point.setMaximumSize(new java.awt.Dimension(50, 18));
        pointage_point.setMinimumSize(new java.awt.Dimension(50, 18));
        pointage_point.setPreferredSize(new java.awt.Dimension(50, 18));
        pointage_point.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointage_pointActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Pointage");

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        pajouter2.setBackground(new java.awt.Color(0, 102, 102));
        pajouter2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pajouter2.setForeground(new java.awt.Color(255, 255, 255));
        pajouter2.setMaximumSize(new java.awt.Dimension(250, 40));
        pajouter2.setMinimumSize(new java.awt.Dimension(250, 40));
        pajouter2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pajouter2MousePressed(evt);
            }
        });

        ajouter2.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        ajouter2.setForeground(new java.awt.Color(255, 255, 255));
        ajouter2.setText("AJOUTER");
        ajouter2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ajouter2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout pajouter2Layout = new javax.swing.GroupLayout(pajouter2);
        pajouter2.setLayout(pajouter2Layout);
        pajouter2Layout.setHorizontalGroup(
            pajouter2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pajouter2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(ajouter2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pajouter2Layout.setVerticalGroup(
            pajouter2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pajouter2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ajouter2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        psupprimer2.setBackground(new java.awt.Color(0, 102, 102));
        psupprimer2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        psupprimer2.setForeground(new java.awt.Color(255, 255, 255));
        psupprimer2.setMaximumSize(new java.awt.Dimension(250, 40));
        psupprimer2.setMinimumSize(new java.awt.Dimension(250, 40));
        psupprimer2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                psupprimer2MousePressed(evt);
            }
        });

        supprimer2.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        supprimer2.setForeground(new java.awt.Color(255, 255, 255));
        supprimer2.setText("SUPPRIMER");
        supprimer2.setMaximumSize(new java.awt.Dimension(250, 40));
        supprimer2.setMinimumSize(new java.awt.Dimension(250, 40));
        supprimer2.setPreferredSize(new java.awt.Dimension(250, 40));
        supprimer2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                supprimer2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout psupprimer2Layout = new javax.swing.GroupLayout(psupprimer2);
        psupprimer2.setLayout(psupprimer2Layout);
        psupprimer2Layout.setHorizontalGroup(
            psupprimer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(psupprimer2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(supprimer2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        psupprimer2Layout.setVerticalGroup(
            psupprimer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(psupprimer2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(supprimer2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pmodifier2.setBackground(new java.awt.Color(0, 102, 102));
        pmodifier2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pmodifier2.setForeground(new java.awt.Color(255, 255, 255));
        pmodifier2.setMaximumSize(new java.awt.Dimension(250, 40));
        pmodifier2.setMinimumSize(new java.awt.Dimension(250, 40));
        pmodifier2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pmodifier2MousePressed(evt);
            }
        });

        modifier2.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        modifier2.setForeground(new java.awt.Color(255, 255, 255));
        modifier2.setText("MODIFIER");
        modifier2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                modifier2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout pmodifier2Layout = new javax.swing.GroupLayout(pmodifier2);
        pmodifier2.setLayout(pmodifier2Layout);
        pmodifier2Layout.setHorizontalGroup(
            pmodifier2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pmodifier2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(modifier2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pmodifier2Layout.setVerticalGroup(
            pmodifier2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pmodifier2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(modifier2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pannuler2.setBackground(new java.awt.Color(0, 102, 102));
        pannuler2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pannuler2.setForeground(new java.awt.Color(255, 255, 255));
        pannuler2.setMaximumSize(new java.awt.Dimension(250, 40));
        pannuler2.setMinimumSize(new java.awt.Dimension(250, 40));
        pannuler2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pannuler2MousePressed(evt);
            }
        });

        annuler2.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        annuler2.setForeground(new java.awt.Color(255, 255, 255));
        annuler2.setText("ANNULER");
        annuler2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                annuler2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout pannuler2Layout = new javax.swing.GroupLayout(pannuler2);
        pannuler2.setLayout(pannuler2Layout);
        pannuler2Layout.setHorizontalGroup(
            pannuler2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannuler2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(annuler2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pannuler2Layout.setVerticalGroup(
            pannuler2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannuler2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(annuler2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pannuler2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(psupprimer2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pmodifier2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pajouter2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(pajouter2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pmodifier2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pannuler2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(psupprimer2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        table2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date de Pointage", "N° Employé", "Pointage"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table2.setGridColor(new java.awt.Color(0, 102, 102));
        table2.setSelectionBackground(new java.awt.Color(0, 102, 102));
        table2.setShowHorizontalLines(true);
        table2.setShowVerticalLines(true);
        table2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table2MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(table2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pointage_point, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pointage_empl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pointage_date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(87, 87, 87)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(pointage_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(pointage_empl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4)))
                                    .addComponent(jLabel3))
                                .addGap(35, 35, 35)
                                .addComponent(pointage_point, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void absenceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_absenceMousePressed
        Abscence absence= new Abscence();
        absence.setVisible(true);
    }//GEN-LAST:event_absenceMousePressed

    private void pabsenceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pabsenceMousePressed
         Abscence absence= new Abscence();
        absence.setVisible(true);
    }//GEN-LAST:event_pabsenceMousePressed

    private void empl2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empl2MousePressed
        Employes au=new Employes();
        au.setVisible(true);
    }//GEN-LAST:event_empl2MousePressed

    private void empl2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_empl2KeyReleased

    }//GEN-LAST:event_empl2KeyReleased

    private void EmplMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmplMousePressed
        Employes au=new Employes();
        au.setVisible(true);
    }//GEN-LAST:event_EmplMousePressed

    private void EmplKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmplKeyReleased

    }//GEN-LAST:event_EmplKeyReleased

    private void point2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_point2MousePressed
        Pointage au=new Pointage();
        au.setVisible(true);
    }//GEN-LAST:event_point2MousePressed

    private void point2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_point2KeyReleased

    }//GEN-LAST:event_point2KeyReleased

    private void PointageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PointageMousePressed
        Pointage au=new Pointage();
        au.setVisible(true);
    }//GEN-LAST:event_PointageMousePressed

    private void PointageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PointageKeyReleased

    }//GEN-LAST:event_PointageKeyReleased

    private void Conge2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Conge2MousePressed
        Conge au=new Conge();
        au.setVisible(true);
    }//GEN-LAST:event_Conge2MousePressed

    private void CONGEMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CONGEMousePressed
        Conge au=new Conge();
        au.setVisible(true);
    }//GEN-LAST:event_CONGEMousePressed

    private void pointage_emplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointage_emplActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pointage_emplActionPerformed

    private void pointage_pointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointage_pointActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pointage_pointActionPerformed

    private void ajouter2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajouter2MousePressed
        Connection con;
        Functions action=new Functions();
        con=action.Connect_db();

        action.InsertTable2(con, pointage_date, pointage_empl, pointage_point);
        action.Affiche2(con, table2);
    }//GEN-LAST:event_ajouter2MousePressed

    private void pajouter2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pajouter2MousePressed
        Connection con;
        Functions action=new Functions();
        con=action.Connect_db();

        action.InsertTable2(con, pointage_date, pointage_empl, pointage_point);
        action.Affiche2(con, table2);
    }//GEN-LAST:event_pajouter2MousePressed

    private void supprimer2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supprimer2MousePressed
        Connection con;
        Functions action=new Functions();
        con=action.Connect_db();

        action.Delete2(con, table2, pointage_empl);
        action.Affiche2(con, table2);
    }//GEN-LAST:event_supprimer2MousePressed

    private void psupprimer2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psupprimer2MousePressed
        Connection con;
        Functions action=new Functions();
        con=action.Connect_db();
        action.Delete2(con, table2, pointage_empl);
        action.Affiche2(con, table2);
    }//GEN-LAST:event_psupprimer2MousePressed

    private void modifier2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifier2MousePressed
        Connection con;
        Functions action=new Functions();
        con=action.Connect_db();
        action.Update_22(con, pointage_date, pointage_empl, pointage_point);
        action.Affiche2(con, table2);
    }//GEN-LAST:event_modifier2MousePressed

    private void pmodifier2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pmodifier2MousePressed
        Connection con;
        Functions action=new Functions();
        con=action.Connect_db();

        action.Affiche2(con, table2);
        action.Update_22(con, pointage_date, pointage_empl, pointage_point);
        action.Affiche2(con, table2);
    }//GEN-LAST:event_pmodifier2MousePressed

    private void table2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table2MouseClicked
        try {
            Connection con;
            Functions action=new Functions();
            con=action.Connect_db();
            String id=action.getId2(con, table2);

            action.Update_12(con, id, table2, pointage_date, pointage_empl, pointage_point);
            action.Affiche2(con, table2);
        } catch (SQLException ex) {
            Logger.getLogger(Pointage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(Pointage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_table2MouseClicked

    private void table2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table2MousePressed

    }//GEN-LAST:event_table2MousePressed

    private void annuler2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_annuler2MousePressed
        Connection con;
        Functions action=new Functions();
        con=action.Connect_db();

        action.Annuler2(pointage_date, pointage_empl, pointage_point);
    }//GEN-LAST:event_annuler2MousePressed

    private void pannuler2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pannuler2MousePressed
        Connection con;
        Functions action=new Functions();
        con=action.Connect_db();

        action.Annuler2(pointage_date, pointage_empl, pointage_point);
    }//GEN-LAST:event_pannuler2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pointage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pointage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pointage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pointage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pointage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CONGE;
    private javax.swing.JLabel Conge2;
    private javax.swing.JPanel Empl;
    private javax.swing.JPanel Pointage;
    private javax.swing.JLabel absence;
    private javax.swing.JLabel ajouter2;
    private javax.swing.JLabel annuler2;
    private javax.swing.JLabel empl2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel modifier2;
    private javax.swing.JPanel pabsence;
    private javax.swing.JPanel pajouter2;
    private javax.swing.JPanel pannuler2;
    private javax.swing.JPanel pmodifier2;
    private javax.swing.JLabel point2;
    private com.toedter.calendar.JDateChooser pointage_date;
    private javax.swing.JTextField pointage_empl;
    private javax.swing.JTextField pointage_point;
    private javax.swing.JPanel psupprimer2;
    private javax.swing.JLabel supprimer2;
    private javax.swing.JTable table2;
    // End of variables declaration//GEN-END:variables
}
